// app/components/quotes/ProductTweakModal.vue
<template>
  <Teleport to="body">
    <Transition name="modal">
      <div
        v-if="isOpen"
        class="fixed inset-0 z-50 flex items-center justify-center p-4"
        role="dialog"
        aria-modal="true"
      >
        <!-- Backdrop -->
        <div
          class="absolute inset-0 bg-black/50 backdrop-blur-sm"
          @click="isOpen = false"
        />

        <!-- Modal panel -->
        <div
          class="modal-panel relative w-full max-w-lg max-h-[90vh] overflow-y-auto bg-[var(--p-surface)] rounded-2xl shadow-2xl z-10"
          @click.stop
        >
      <!-- Header -->
      <div class="sticky top-0 z-10 bg-[var(--p-surface)]/95 backdrop-blur-sm border-b border-[var(--p-border)] px-6 py-4 rounded-t-2xl">
        <div class="flex items-start justify-between gap-4">
          <div>
            <h2 class="text-lg font-bold text-[var(--p-text)]">
              Tweak Quote — {{ product.name }}
            </h2>
            <p class="text-sm text-[var(--p-text-muted)] mt-0.5">
              Customize paper, quantity, finishing, and other options before adding to your quote.
            </p>
          </div>
          <button
            class="rounded-lg p-1.5 text-[var(--p-text-muted)] hover:text-[var(--p-text)] hover:bg-[var(--p-surface-sunken)] transition-colors"
            @click="isOpen = false"
          >
            <UIcon name="i-lucide-x" class="h-5 w-5" />
          </button>
        </div>
      </div>

      <!-- Body -->
      <div class="min-h-[200px] p-6 space-y-6">
        <!-- Success message -->
        <div
          v-if="successMessage"
          class="rounded-xl border border-green-200 dark:border-green-800 bg-green-50 dark:bg-green-950/30 p-4 flex items-center gap-3"
        >
          <div class="w-8 h-8 rounded-full bg-green-100 dark:bg-green-900 flex items-center justify-center">
            <UIcon name="i-lucide-check" class="h-5 w-5 text-green-600 dark:text-green-400" />
          </div>
          <p class="text-sm font-medium text-green-700 dark:text-green-300">{{ successMessage }}</p>
        </div>

        <!-- Loading -->
        <div v-else-if="loading" class="flex flex-col items-center justify-center py-12 text-[var(--p-text-muted)]">
          <UIcon name="i-lucide-loader-2" class="h-8 w-8 animate-spin mb-3" />
          <p class="text-sm">Loading options…</p>
        </div>

        <!-- Error -->
        <div
          v-else-if="loadError"
          class="rounded-lg border border-red-300 dark:border-red-800 bg-red-50 dark:bg-red-950/30 p-4 text-sm text-red-700 dark:text-red-300"
        >
          <p class="font-semibold">Could not open quote options.</p>
          <p class="mt-1">{{ loadError }}</p>
          <div class="mt-3 flex gap-2">
            <UButton variant="soft" color="error" size="sm" @click="loadShopData">Retry</UButton>
            <UButton variant="ghost" size="sm" @click="isOpen = false">Close</UButton>
          </div>
        </div>

        <!-- Form -->
        <div v-else class="space-y-6">
        <!-- Product info row -->
        <div class="flex items-center gap-4 rounded-xl bg-[var(--p-surface-sunken)] p-4">
          <div v-if="imageUrl" class="w-16 h-16 rounded-lg overflow-hidden shrink-0 border border-[var(--p-border)]">
            <img :src="imageUrl" :alt="product.name" class="w-full h-full object-cover" />
          </div>
          <div v-else class="w-16 h-16 rounded-lg bg-[var(--p-border)] flex items-center justify-center shrink-0">
            <UIcon name="i-lucide-package" class="h-8 w-8 text-[var(--p-text-muted)]" />
          </div>
          <div class="min-w-0 flex-1">
            <p class="font-semibold text-[var(--p-text)] truncate">{{ product.name }}</p>
            <p v-if="product.category" class="text-xs text-[var(--p-text-muted)]">{{ product.category }}</p>
            <div class="flex flex-wrap gap-1.5 mt-1">
              <UBadge v-if="product.final_size" variant="soft" color="neutral" size="xs">{{ product.final_size }}</UBadge>
              <UBadge v-if="product.imposition_summary" variant="soft" color="neutral" size="xs">{{ product.imposition_summary }}</UBadge>
              <UBadge variant="soft" color="primary" size="xs">{{ product.pricing_mode === 'LARGE_FORMAT' ? 'Large Format' : 'Sheet' }}</UBadge>
            </div>
          </div>
        </div>

        <!-- Form -->
        <form class="space-y-5" @submit.prevent="onSubmit">
          <!-- Quantity -->
          <div>
            <label class="block text-sm font-medium text-[var(--p-text-dim)] mb-1.5">Quantity</label>
            <div class="flex items-center gap-2">
              <UButton variant="soft" color="neutral" size="sm" icon="i-lucide-minus" @click="form.quantity = Math.max(minQty, form.quantity - 50)" />
              <input
                v-model.number="form.quantity"
                type="number"
                :min="minQty"
                class="w-24 text-center rounded-lg border border-[var(--p-border)] bg-[var(--p-surface)] px-3 py-2 text-sm font-medium text-[var(--p-text)] focus:outline-none focus:ring-2 focus:ring-flamingo-400"
                @blur="form.quantity = Math.max(minQty, form.quantity || minQty)"
              />
              <UButton variant="soft" color="neutral" size="sm" icon="i-lucide-plus" @click="form.quantity += 50" />
              <span class="text-xs text-[var(--p-text-muted)]">min {{ minQty }}</span>
            </div>
          </div>

          <!-- Sides (simplex / duplex) -->
          <div v-if="product.pricing_mode === 'SHEET'">
            <label class="block text-sm font-medium text-[var(--p-text-dim)] mb-1.5">Sides</label>
            <div class="grid grid-cols-2 gap-2">
              <button
                type="button"
                class="rounded-lg border px-3 py-2 text-sm font-medium transition-all"
                :class="form.sides === 'SIMPLEX'
                  ? 'border-flamingo-400 bg-flamingo-50 dark:bg-flamingo-900/20 text-flamingo-700 dark:text-flamingo-300'
                  : 'border-[var(--p-border)] text-[var(--p-text-dim)] hover:border-[var(--p-border-dim)]'"
                @click="form.sides = 'SIMPLEX'"
              >
                Single-sided
              </button>
              <button
                type="button"
                class="rounded-lg border px-3 py-2 text-sm font-medium transition-all"
                :class="form.sides === 'DUPLEX'
                  ? 'border-flamingo-400 bg-flamingo-50 dark:bg-flamingo-900/20 text-flamingo-700 dark:text-flamingo-300'
                  : 'border-[var(--p-border)] text-[var(--p-text-dim)] hover:border-[var(--p-border-dim)]'"
                @click="form.sides = 'DUPLEX'"
              >
                Double-sided
              </button>
            </div>
          </div>

          <!-- Color mode -->
          <div v-if="product.pricing_mode === 'SHEET'">
            <label class="block text-sm font-medium text-[var(--p-text-dim)] mb-1.5">Color</label>
            <div class="grid grid-cols-2 gap-2">
              <button
                type="button"
                class="rounded-lg border px-3 py-2 text-sm font-medium transition-all"
                :class="form.color_mode === 'COLOR'
                  ? 'border-flamingo-400 bg-flamingo-50 dark:bg-flamingo-900/20 text-flamingo-700 dark:text-flamingo-300'
                  : 'border-[var(--p-border)] text-[var(--p-text-dim)] hover:border-[var(--p-border-dim)]'"
                @click="form.color_mode = 'COLOR'"
              >
                <UIcon name="i-lucide-palette" class="h-4 w-4 mr-1 inline" />
                Color
              </button>
              <button
                type="button"
                class="rounded-lg border px-3 py-2 text-sm font-medium transition-all"
                :class="form.color_mode === 'BW'
                  ? 'border-flamingo-400 bg-flamingo-50 dark:bg-flamingo-900/20 text-flamingo-700 dark:text-flamingo-300'
                  : 'border-[var(--p-border)] text-[var(--p-text-dim)] hover:border-[var(--p-border-dim)]'"
                @click="form.color_mode = 'BW'"
              >
                B&W
              </button>
            </div>
          </div>

          <!-- Paper (SHEET mode) -->
          <div v-if="product.pricing_mode === 'SHEET' && papers.length">
            <label class="block text-sm font-medium text-[var(--p-text-dim)] mb-1.5">Paper type / grammage</label>
            <div class="space-y-1.5 max-h-36 overflow-y-auto rounded-lg border border-[var(--p-border)] p-2">
              <label
                v-for="p in papers"
                :key="p.id"
                class="flex items-center gap-3 rounded-lg px-3 py-2 cursor-pointer transition-colors"
                :class="form.paper === p.id ? 'bg-flamingo-50 dark:bg-flamingo-900/20' : 'hover:bg-[var(--p-surface-sunken)]'"
              >
                <input
                  v-model="form.paper"
                  type="radio"
                  :value="p.id"
                  class="accent-flamingo-500"
                />
                <span class="text-sm text-[var(--p-text)]">{{ p.sheet_size }} {{ p.gsm }}gsm {{ p.paper_type }}</span>
                <span class="ml-auto text-xs text-[var(--p-text-muted)]">KES {{ p.selling_price }}</span>
              </label>
            </div>
          </div>

          <!-- Material (LARGE_FORMAT mode) -->
          <div v-if="product.pricing_mode === 'LARGE_FORMAT' && materials.length">
            <label class="block text-sm font-medium text-[var(--p-text-dim)] mb-1.5">Material</label>
            <div class="space-y-1.5 max-h-36 overflow-y-auto rounded-lg border border-[var(--p-border)] p-2">
              <label
                v-for="m in materials"
                :key="m.id"
                class="flex items-center gap-3 rounded-lg px-3 py-2 cursor-pointer transition-colors"
                :class="form.material === m.id ? 'bg-flamingo-50 dark:bg-flamingo-900/20' : 'hover:bg-[var(--p-surface-sunken)]'"
              >
                <input
                  v-model="form.material"
                  type="radio"
                  :value="m.id"
                  class="accent-flamingo-500"
                />
                <span class="text-sm text-[var(--p-text)]">{{ m.material_type ?? m.name }}</span>
                <span class="ml-auto text-xs text-[var(--p-text-muted)]">KES {{ m.selling_price }}/{{ m.unit }}</span>
              </label>
            </div>
          </div>

          <!-- Finishing options -->
          <div v-if="finishingRates.length">
            <label class="block text-sm font-medium text-[var(--p-text-dim)] mb-1.5">Finishing</label>
            <div class="space-y-1.5 max-h-40 overflow-y-auto rounded-lg border border-[var(--p-border)] p-2">
              <label
                v-for="fr in finishingRates"
                :key="fr.id"
                class="flex items-center gap-3 rounded-lg px-3 py-2 cursor-pointer transition-colors hover:bg-[var(--p-surface-sunken)]"
              >
                <UCheckbox
                  :model-value="form.finishings.some(f => f.finishing_rate === fr.id)"
                  @update:model-value="toggleFinishing(fr.id, $event)"
                />
                <span class="text-sm text-[var(--p-text)] flex-1">{{ fr.name }}</span>
                <span class="text-xs text-[var(--p-text-muted)]">KES {{ fr.price }}</span>
              </label>
            </div>
          </div>

          <!-- Hint: complete your quote -->
          <div
            v-if="needsPaperOrFinishing"
            class="rounded-lg border border-amber-200 dark:border-amber-800 bg-amber-50/50 dark:bg-amber-900/20 p-3 text-sm text-amber-800 dark:text-amber-200"
          >
            <p class="font-medium flex items-center gap-2">
              <UIcon name="i-lucide-lightbulb" class="h-4 w-4 shrink-0" />
              For a complete quote
            </p>
            <ul class="mt-1 ml-6 list-disc space-y-0.5 text-amber-700 dark:text-amber-300">
              <li v-if="product.pricing_mode === 'SHEET' && papers.length && !form.paper">Select paper for accurate pricing</li>
              <li v-if="product.pricing_mode === 'LARGE_FORMAT' && materials.length && !form.material">Select material for accurate pricing</li>
              <li v-if="finishingRates.length && !form.finishings.length">Consider adding finishing (lamination, binding, etc.)</li>
            </ul>
          </div>

          <!-- Special instructions -->
          <div>
            <label class="block text-sm font-medium text-[var(--p-text-dim)] mb-1.5">Special instructions</label>
            <UTextarea
              v-model="form.special_instructions"
              placeholder="Any notes for the shop (optional)"
              :rows="2"
            />
          </div>

          <!-- Price preview section -->
          <div class="rounded-xl border border-flamingo-200 dark:border-flamingo-800/50 bg-flamingo-50/50 dark:bg-flamingo-900/10 p-4 space-y-2">
            <p class="text-xs font-semibold uppercase tracking-wider text-flamingo-600 dark:text-flamingo-400">Quote Summary</p>
            <div class="flex justify-between text-sm">
              <span class="text-[var(--p-text-dim)]">Product</span>
              <span class="font-medium text-[var(--p-text)]">{{ product.name }}</span>
            </div>
            <div class="flex justify-between text-sm">
              <span class="text-[var(--p-text-dim)]">Quantity</span>
              <span class="font-medium text-[var(--p-text)]">{{ form.quantity }} pcs</span>
            </div>
            <div v-if="product.pricing_mode === 'SHEET'" class="flex justify-between text-sm">
              <span class="text-[var(--p-text-dim)]">Sides</span>
              <span class="font-medium text-[var(--p-text)]">{{ form.sides === 'DUPLEX' ? 'Double-sided' : 'Single-sided' }}</span>
            </div>
            <div v-if="product.pricing_mode === 'SHEET'" class="flex justify-between text-sm">
              <span class="text-[var(--p-text-dim)]">Color</span>
              <span class="font-medium text-[var(--p-text)]">{{ form.color_mode === 'COLOR' ? 'Full Color' : 'Black & White' }}</span>
            </div>
            <div v-if="selectedPaperLabel" class="flex justify-between text-sm">
              <span class="text-[var(--p-text-dim)]">Paper</span>
              <span class="font-medium text-[var(--p-text)]">{{ selectedPaperLabel }}</span>
            </div>
            <div v-if="selectedMaterialLabel" class="flex justify-between text-sm">
              <span class="text-[var(--p-text-dim)]">Material</span>
              <span class="font-medium text-[var(--p-text)]">{{ selectedMaterialLabel }}</span>
            </div>
            <div v-if="selectedFinishingLabels.length" class="flex justify-between text-sm">
              <span class="text-[var(--p-text-dim)]">Finishing</span>
              <span class="font-medium text-[var(--p-text)]">{{ selectedFinishingLabels.join(', ') }}</span>
            </div>
            <div v-if="product.price_hint?.can_calculate || product.price_range_est?.can_calculate" class="border-t border-flamingo-200/60 dark:border-flamingo-800/30 pt-2 space-y-1">
              <div v-if="tweakPriceSummary" class="flex justify-between items-baseline">
                <span class="font-semibold text-[var(--p-text)]">Est. total</span>
                <span class="text-lg font-bold text-flamingo-600 dark:text-flamingo-400">
                  {{ tweakPriceSummary.totalLine }}
                </span>
              </div>
              <div v-if="tweakPriceSummary?.perUnitLine" class="flex justify-between text-sm text-[var(--p-text-muted)]">
                <span>Per item</span>
                <span>{{ tweakPriceSummary.perUnitLine }}</span>
              </div>
              <div v-else-if="product.price_hint?.price_display" class="flex justify-between">
                <span class="font-semibold text-[var(--p-text)]">Est. price</span>
                <span class="text-lg font-bold text-flamingo-600 dark:text-flamingo-400">
                  {{ product.price_hint.price_display }}
                </span>
              </div>
            </div>
            <p class="text-xs text-[var(--p-text-muted)]">Final price computed by the shop after submission.</p>
          </div>

          <!-- Actions -->
          <div class="flex gap-3 pt-2">
            <UButton variant="soft" color="neutral" class="flex-1" @click="isOpen = false">
              Cancel
            </UButton>
            <UButton type="submit" color="primary" class="flex-1" :loading="submitting">
              <UIcon name="i-lucide-plus" class="h-4 w-4 mr-1" />
              Add to Quote
            </UButton>
          </div>
        </form>
        </div>
      </div>
    </div>
    </div>
    </Transition>
  </Teleport>
</template>

<script setup lang="ts">
import type { Product, Paper, FinishingRate } from '~/shared/types'
import type { QuoteItemFinishingPayload } from '~/services/quoteDraft'
import { useApi, usePublicApi } from '~/shared/api'
import { API } from '~/shared/api-paths'

interface MaterialItem {
  id: number
  material_type?: string
  name?: string
  unit: string
  selling_price: string
  is_active: boolean
}

const props = defineProps<{
  product: Product
  shopSlug: string
}>()

const { priceDisplaySummary, tweakPriceDisplaySummary } = useProductPriceDisplay()

const hasAllRequiredOptions = computed(() => {
  if (props.product.pricing_mode === 'SHEET' && papers.value.length > 0 && !form.paper) return false
  if (props.product.pricing_mode === 'LARGE_FORMAT' && materials.value.length > 0 && !form.material) return false
  return true
})

const tweakPriceSummary = computed(() => {
  if (hasAllRequiredOptions.value) {
    const precise = tweakPriceDisplaySummary(props.product, form, finishingRates.value)
    if (precise) return precise
  }
  return priceDisplaySummary(props.product)
})

const emit = defineEmits<{
  (e: 'added'): void
}>()

const isOpen = defineModel<boolean>({ default: false })

const { getMediaUrl } = useApi()
const publicApi = usePublicApi()

const submitting = ref(false)
const successMessage = ref('')
const loading = ref(false)
const loadError = ref('')
const papers = ref<Paper[]>([])
const materials = ref<MaterialItem[]>([])
const finishingRates = ref<FinishingRate[]>([])

const minQty = computed(() => props.product.min_quantity || 100)

const imageUrl = computed(() => {
  const path = props.product.primary_image
  if (!path) return null
  if (path.startsWith('http')) return path
  return getMediaUrl(path)
})

interface TweakForm {
  quantity: number
  sides: 'SIMPLEX' | 'DUPLEX'
  color_mode: 'BW' | 'COLOR'
  paper: number | null
  material: number | null
  finishings: QuoteItemFinishingPayload[]
  special_instructions: string
}

const form = reactive<TweakForm>({
  quantity: minQty.value,
  sides: (props.product.default_sides as 'SIMPLEX' | 'DUPLEX') || 'SIMPLEX',
  color_mode: 'COLOR',
  paper: null,
  material: null,
  finishings: [],
  special_instructions: '',
})

const selectedPaperLabel = computed(() => {
  if (!form.paper) return null
  const p = papers.value.find(x => x.id === form.paper)
  return p ? `${p.sheet_size} ${p.gsm}gsm ${p.paper_type}` : null
})

const selectedMaterialLabel = computed(() => {
  if (!form.material) return null
  const m = materials.value.find(x => x.id === form.material)
  return m ? (m.material_type ?? m.name ?? '') : null
})

const selectedFinishingLabels = computed(() => {
  return form.finishings
    .map(f => finishingRates.value.find(r => r.id === f.finishing_rate)?.name)
    .filter(Boolean) as string[]
})

const needsPaperOrFinishing = computed(() => {
  if (props.product.pricing_mode === 'SHEET' && papers.value.length && !form.paper) return true
  if (props.product.pricing_mode === 'LARGE_FORMAT' && materials.value.length && !form.material) return true
  if (finishingRates.value.length && !form.finishings.length) return true
  return false
})

function toggleFinishing(id: number, checked: boolean) {
  if (checked) {
    form.finishings.push({ finishing_rate: id })
  } else {
    form.finishings = form.finishings.filter(f => f.finishing_rate !== id)
  }
}

function resetForm() {
  form.quantity = minQty.value
  form.sides = (props.product.default_sides as 'SIMPLEX' | 'DUPLEX') || 'SIMPLEX'
  form.color_mode = 'COLOR'
  form.paper = null
  form.material = null
  form.special_instructions = ''

  const defaultFinishings = (props.product.finishing_options ?? [])
    .filter(o => o.is_default)
    .map(o => ({ finishing_rate: o.finishing_rate }))
  form.finishings = defaultFinishings
  successMessage.value = ''
}

interface PublicProductOptions {
  available_papers?: Array<{ id: number; sheet_size: string; gsm: number; paper_type: string; selling_price: string }>
  available_materials?: Array<{ id: number; material_type?: string; unit: string; selling_price: string }>
  available_finishings?: Array<{ id: number; name: string; price: string; charge_unit?: string }>
}

async function loadShopData() {
  const slug = props.shopSlug
  const productId = props.product?.id
  if (!slug && !productId) {
    loadError.value = 'No shop or product selected.'
    return
  }

  loading.value = true
  loadError.value = ''

  // Prefer public product options (no auth) for gallery / unauthenticated users
  if (productId) {
    try {
      const opts = await publicApi<PublicProductOptions>(API.publicProductOptions(productId))
      papers.value = (opts.available_papers ?? []).map((p) => ({
        id: p.id,
        shop: 0,
        sheet_size: p.sheet_size,
        gsm: p.gsm,
        paper_type: p.paper_type,
        selling_price: p.selling_price,
        buying_price: '0',
        is_active: true,
      }))
      materials.value = (opts.available_materials ?? []).map((m) => ({
        id: m.id,
        material_type: m.material_type,
        name: m.material_type,
        unit: m.unit,
        selling_price: m.selling_price,
        is_active: true,
      }))
      finishingRates.value = (opts.available_finishings ?? []).map((f) => ({
        id: f.id,
        name: f.name,
        price: f.price,
        charge_unit: (f.charge_unit as FinishingRate['charge_unit']) ?? 'PER_PIECE',
        is_active: true,
      }))
    } catch (err: unknown) {
      const msg = err && typeof err === 'object' && 'data' in err
        ? (err as { data?: { message?: string } }).data?.message
        : err instanceof Error ? err.message : 'Unknown error loading product options.'
      loadError.value = msg || 'Could not load product options.'
    } finally {
      loading.value = false
      return
    }
  }

  if (!slug) {
    loadError.value = 'No shop selected.'
    loading.value = false
    return
  }
  try {
    const api = useApi()
    const [papersData, finishData, materialsData] = await Promise.all([
      api<Paper[] | { results: Paper[] }>(API.shopPapers(slug)),
      api<FinishingRate[] | { results: FinishingRate[] }>(API.shopFinishingRates(slug)),
      api<MaterialItem[] | { results: MaterialItem[] }>(API.shopMaterials(slug)),
    ])
    papers.value = extractArray(papersData)
    finishingRates.value = extractArray(finishData)
    materials.value = extractArray(materialsData)
  } catch (err: unknown) {
    papers.value = []
    finishingRates.value = []
    materials.value = []
    const msg = err && typeof err === 'object' && 'data' in err
      ? (err as { data?: { message?: string } }).data?.message
      : err instanceof Error ? err.message : 'Could not load shop options.'
    loadError.value = msg || 'Could not load papers, materials, or finishing options.'
  } finally {
    loading.value = false
  }
}

function extractArray<T>(data: T[] | { results: T[] }): T[] {
  if (Array.isArray(data)) return data
  if (data && typeof data === 'object' && Array.isArray((data as { results?: T[] }).results)) {
    return (data as { results: T[] }).results
  }
  return []
}

async function onSubmit() {
  const { useQuoteDraftStore } = await import('~/stores/quoteDraft')
  const quoteDraftStore = useQuoteDraftStore()
  submitting.value = true
  try {
    await quoteDraftStore.addTweakedProductToQuote(props.shopSlug, {
      item_type: 'PRODUCT',
      product: props.product.id,
      quantity: Math.max(minQty.value, form.quantity),
      pricing_mode: props.product.pricing_mode,
      paper: form.paper ?? undefined,
      material: form.material ?? undefined,
      sides: form.sides,
      color_mode: form.color_mode,
      finishings: form.finishings.length ? form.finishings : undefined,
      special_instructions: form.special_instructions.trim() || undefined,
    })
    successMessage.value = `${props.product.name} added to your quote!`
    emit('added')
    setTimeout(() => { isOpen.value = false }, 1200)
  } catch (err) {
    const toast = useToast()
    toast.add({
      title: 'Could not add to quote',
      description: err instanceof Error ? err.message : 'Please sign in to add to your quote.',
      color: 'error',
    })
  } finally {
    submitting.value = false
  }
}

// When open: reset form, load data, lock body scroll. When closed: restore scroll.
watch(isOpen, (open) => {
  if (open) {
    resetForm()
    loadShopData()
    document.body.style.overflow = 'hidden'
  } else {
    document.body.style.overflow = ''
  }
}, { immediate: true })

// Escape key to close
function onKeydown(e: KeyboardEvent) {
  if (e.key === 'Escape') isOpen.value = false
}
watch(isOpen, (open) => {
  if (open) {
    document.addEventListener('keydown', onKeydown)
  } else {
    document.removeEventListener('keydown', onKeydown)
  }
}, { immediate: true })

onUnmounted(() => {
  document.body.style.overflow = ''
})
</script>

// final-modal-printy/src/components/ProductTweakModal.tsx
import { useState, useEffect, useCallback, useMemo } from 'react'
import {
  X, Loader2, Package, Minus, Plus, Palette, Lightbulb,
  Check, AlertCircle
} from 'lucide-react'
import { cn } from '../utils/cn'
import type { Product, Paper, MaterialItem, FinishingRate, TweakForm, QuoteItemFinishingPayload } from '../types'
import { getShopDataForProduct } from '../data/mockData'
import { useQuote } from '../context/QuoteContext'

interface Props {
  product: Product
  shopSlug: string
  open: boolean
  onClose: () => void
  onAdded?: () => void
}

export default function ProductTweakModal({ product, shopSlug: _shopSlug, open, onClose, onAdded }: Props) {
  const { addItem } = useQuote()
  const [loading, setLoading] = useState(false)
  const [loadError, setLoadError] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [papers, setPapers] = useState<Paper[]>([])
  const [materials, setMaterials] = useState<MaterialItem[]>([])
  const [finishingRates, setFinishingRates] = useState<FinishingRate[]>([])
  const [successMessage, setSuccessMessage] = useState('')

  const minQty = product.min_quantity || 100

  const [form, setForm] = useState<TweakForm>({
    quantity: minQty,
    sides: (product.default_sides as 'SIMPLEX' | 'DUPLEX') || 'SIMPLEX',
    color_mode: 'COLOR',
    paper: null,
    material: null,
    finishings: [],
    special_instructions: '',
  })

  const updateForm = useCallback((updates: Partial<TweakForm>) => {
    setForm(prev => ({ ...prev, ...updates }))
  }, [])

  const resetForm = useCallback(() => {
    const defaultFinishings: QuoteItemFinishingPayload[] = (product.finishing_options ?? [])
      .filter(o => o.is_default)
      .map(o => ({ finishing_rate: o.finishing_rate }))

    setForm({
      quantity: minQty,
      sides: (product.default_sides as 'SIMPLEX' | 'DUPLEX') || 'SIMPLEX',
      color_mode: 'COLOR',
      paper: null,
      material: null,
      finishings: defaultFinishings,
      special_instructions: '',
    })
    setSuccessMessage('')
  }, [product, minQty])

  const loadShopData = useCallback(async () => {
    setLoading(true)
    setLoadError('')
    try {
      // Simulate API call delay
      await new Promise(resolve => setTimeout(resolve, 600))
      const data = getShopDataForProduct(product)
      setPapers(data.papers)
      setMaterials(data.materials)
      setFinishingRates(data.finishings)
    } catch {
      setLoadError('Could not load product options.')
    } finally {
      setLoading(false)
    }
  }, [product])

  useEffect(() => {
    if (open) {
      resetForm()
      loadShopData()
      document.body.style.overflow = 'hidden'
    } else {
      document.body.style.overflow = ''
    }
    return () => { document.body.style.overflow = '' }
  }, [open, resetForm, loadShopData])

  const toggleFinishing = useCallback((id: number, checked: boolean) => {
    setForm(prev => {
      if (checked) {
        return { ...prev, finishings: [...prev.finishings, { finishing_rate: id }] }
      } else {
        return { ...prev, finishings: prev.finishings.filter(f => f.finishing_rate !== id) }
      }
    })
  }, [])

  const selectedPaperLabel = useMemo(() => {
    if (!form.paper) return null
    const p = papers.find(x => x.id === form.paper)
    return p ? `${p.sheet_size} ${p.gsm}gsm ${p.paper_type}` : null
  }, [form.paper, papers])

  const selectedMaterialLabel = useMemo(() => {
    if (!form.material) return null
    const m = materials.find(x => x.id === form.material)
    return m ? (m.material_type ?? m.name ?? '') : null
  }, [form.material, materials])

  const selectedFinishingLabels = useMemo(() => {
    return form.finishings
      .map(f => finishingRates.find(r => r.id === f.finishing_rate)?.name)
      .filter(Boolean) as string[]
  }, [form.finishings, finishingRates])

  const needsPaperOrFinishing = useMemo(() => {
    if (product.pricing_mode === 'SHEET' && papers.length && !form.paper) return true
    if (product.pricing_mode === 'LARGE_FORMAT' && materials.length && !form.material) return true
    if (finishingRates.length && !form.finishings.length) return true
    return false
  }, [product.pricing_mode, papers, materials, finishingRates, form])

  const estimatedTotal = useMemo(() => {
    if (!product.price_hint?.can_calculate) return null
    let base = product.price_hint.total || 0
    // Adjust based on quantity ratio
    const defaultQty = product.min_quantity || 100
    const ratio = form.quantity / defaultQty
    let total = base * ratio

    // Duplex markup
    if (form.sides === 'DUPLEX' && product.default_sides !== 'DUPLEX') {
      total *= 1.4
    }

    // Add finishing costs
    form.finishings.forEach(f => {
      const rate = finishingRates.find(r => r.id === f.finishing_rate)
      if (rate) {
        const price = parseFloat(rate.price) || 0
        if (rate.charge_unit === 'FLAT') {
          total += price
        } else {
          total += price * form.quantity
        }
      }
    })

    return {
      total: Math.round(total),
      perUnit: Math.round(total / form.quantity * 100) / 100,
    }
  }, [product, form, finishingRates])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setSubmitting(true)
    try {
      await new Promise(resolve => setTimeout(resolve, 400))

      const selectedPaper = form.paper ? papers.find(p => p.id === form.paper) : null
      const selectedMaterial = form.material ? materials.find(m => m.id === form.material) : null
      const selectedFinishings = form.finishings
        .map(f => finishingRates.find(r => r.id === f.finishing_rate))
        .filter(Boolean) as FinishingRate[]

      addItem({
        product,
        quantity: Math.max(minQty, form.quantity),
        sides: form.sides,
        color_mode: form.color_mode,
        paper: selectedPaper,
        material: selectedMaterial,
        finishings: selectedFinishings,
        special_instructions: form.special_instructions.trim() || undefined,
      })

      setSuccessMessage(`${product.name} added to your quote!`)
      onAdded?.()

      setTimeout(() => {
        onClose()
      }, 1200)
    } catch {
      setLoadError('Could not add to quote. Please try again.')
    } finally {
      setSubmitting(false)
    }
  }

  if (!open) return null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/50 backdrop-blur-sm transition-opacity"
        onClick={onClose}
      />

      {/* Modal panel */}
      <div className="relative w-[calc(100vw-2rem)] max-w-lg max-h-[90vh] overflow-y-auto bg-white dark:bg-stone-900 rounded-2xl shadow-2xl animate-in fade-in zoom-in-95">
        {/* Header */}
        <div className="sticky top-0 z-10 bg-white/95 dark:bg-stone-900/95 backdrop-blur-sm border-b border-stone-200 dark:border-stone-700 px-6 py-4 rounded-t-2xl">
          <div className="flex items-start justify-between gap-4">
            <div>
              <h2 className="text-lg font-bold text-stone-800 dark:text-stone-100">
                Tweak Quote — {product.name}
              </h2>
              <p className="text-sm text-stone-500 dark:text-stone-400 mt-0.5">
                Customize paper, quantity, finishing, and other options before adding to your quote.
              </p>
            </div>
            <button
              onClick={onClose}
              className="rounded-lg p-1.5 text-stone-400 hover:text-stone-600 dark:hover:text-stone-300 hover:bg-stone-100 dark:hover:bg-stone-800 transition-colors"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* Body */}
        <div className="min-h-[200px] p-6 space-y-6">
          {/* Success Message */}
          {successMessage && (
            <div className="rounded-xl border border-green-200 dark:border-green-800 bg-green-50 dark:bg-green-950/30 p-4 flex items-center gap-3">
              <div className="w-8 h-8 rounded-full bg-green-100 dark:bg-green-900 flex items-center justify-center">
                <Check className="h-5 w-5 text-green-600 dark:text-green-400" />
              </div>
              <p className="text-sm font-medium text-green-700 dark:text-green-300">{successMessage}</p>
            </div>
          )}

          {/* Loading state */}
          {loading && (
            <div className="flex flex-col items-center justify-center py-12 text-stone-400">
              <Loader2 className="h-8 w-8 animate-spin mb-3" />
              <p className="text-sm">Loading options…</p>
            </div>
          )}

          {/* Error state */}
          {!loading && loadError && (
            <div className="rounded-lg border border-red-300 dark:border-red-800 bg-red-50 dark:bg-red-950/30 p-4 text-sm text-red-700 dark:text-red-300">
              <p className="font-semibold flex items-center gap-2">
                <AlertCircle className="h-4 w-4" />
                Could not open quote options.
              </p>
              <p className="mt-1">{loadError}</p>
              <div className="mt-3 flex gap-2">
                <button
                  onClick={loadShopData}
                  className="px-3 py-1.5 text-sm rounded-lg bg-red-100 dark:bg-red-900/50 text-red-700 dark:text-red-300 hover:bg-red-200 dark:hover:bg-red-900 transition-colors"
                >
                  Retry
                </button>
                <button
                  onClick={onClose}
                  className="px-3 py-1.5 text-sm rounded-lg text-stone-600 dark:text-stone-400 hover:bg-stone-100 dark:hover:bg-stone-800 transition-colors"
                >
                  Close
                </button>
              </div>
            </div>
          )}

          {/* Loaded content */}
          {!loading && !loadError && (
            <>
              {/* Product info row */}
              <div className="flex items-center gap-4 rounded-xl bg-stone-50 dark:bg-stone-800/50 p-4">
                <div className="w-16 h-16 rounded-lg bg-stone-200 dark:bg-stone-700 flex items-center justify-center shrink-0 border border-stone-200 dark:border-stone-600 overflow-hidden">
                  {product.primary_image ? (
                    <img src={product.primary_image} alt={product.name} className="w-full h-full object-cover" />
                  ) : (
                    <Package className="h-8 w-8 text-stone-400 dark:text-stone-500" />
                  )}
                </div>
                <div className="min-w-0 flex-1">
                  <p className="font-semibold text-stone-800 dark:text-stone-100 truncate">{product.name}</p>
                  {product.category && (
                    <p className="text-xs text-stone-500 dark:text-stone-400">{product.category}</p>
                  )}
                  <div className="flex flex-wrap gap-1.5 mt-1">
                    {product.final_size && (
                      <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-stone-100 dark:bg-stone-700 text-stone-600 dark:text-stone-300">
                        {product.final_size}
                      </span>
                    )}
                    {product.imposition_summary && (
                      <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-stone-100 dark:bg-stone-700 text-stone-600 dark:text-stone-300">
                        {product.imposition_summary}
                      </span>
                    )}
                    <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-300">
                      {product.pricing_mode === 'LARGE_FORMAT' ? 'Large Format' : 'Sheet'}
                    </span>
                  </div>
                </div>
              </div>

              {/* Form */}
              <form className="space-y-5" onSubmit={handleSubmit}>
                {/* Quantity */}
                <div>
                  <label className="block text-sm font-medium text-stone-600 dark:text-stone-300 mb-1.5">Quantity</label>
                  <div className="flex items-center gap-2">
                    <button
                      type="button"
                      onClick={() => updateForm({ quantity: Math.max(minQty, form.quantity - 50) })}
                      className="p-2 rounded-lg bg-stone-100 dark:bg-stone-800 text-stone-600 dark:text-stone-300 hover:bg-stone-200 dark:hover:bg-stone-700 transition-colors"
                    >
                      <Minus className="h-4 w-4" />
                    </button>
                    <input
                      type="number"
                      value={form.quantity}
                      min={minQty}
                      onChange={e => updateForm({ quantity: parseInt(e.target.value) || minQty })}
                      onBlur={() => updateForm({ quantity: Math.max(minQty, form.quantity || minQty) })}
                      className="w-24 text-center rounded-lg border border-stone-300 dark:border-stone-600 bg-white dark:bg-stone-800 px-3 py-2 text-sm font-medium text-stone-800 dark:text-stone-100 focus:outline-none focus:ring-2 focus:ring-amber-400"
                    />
                    <button
                      type="button"
                      onClick={() => updateForm({ quantity: form.quantity + 50 })}
                      className="p-2 rounded-lg bg-stone-100 dark:bg-stone-800 text-stone-600 dark:text-stone-300 hover:bg-stone-200 dark:hover:bg-stone-700 transition-colors"
                    >
                      <Plus className="h-4 w-4" />
                    </button>
                    <span className="text-xs text-stone-400">min {minQty}</span>
                  </div>
                </div>

                {/* Sides (SHEET mode only) */}
                {product.pricing_mode === 'SHEET' && (
                  <div>
                    <label className="block text-sm font-medium text-stone-600 dark:text-stone-300 mb-1.5">Sides</label>
                    <div className="grid grid-cols-2 gap-2">
                      {(['SIMPLEX', 'DUPLEX'] as const).map(side => (
                        <button
                          key={side}
                          type="button"
                          onClick={() => updateForm({ sides: side })}
                          className={cn(
                            'rounded-lg border px-3 py-2 text-sm font-medium transition-all',
                            form.sides === side
                              ? 'border-amber-400 bg-amber-50 dark:bg-amber-900/20 text-amber-700 dark:text-amber-300 ring-1 ring-amber-400/50'
                              : 'border-stone-200 dark:border-stone-600 text-stone-600 dark:text-stone-300 hover:border-stone-300 dark:hover:border-stone-500'
                          )}
                        >
                          {side === 'SIMPLEX' ? 'Single-sided' : 'Double-sided'}
                        </button>
                      ))}
                    </div>
                  </div>
                )}

                {/* Color mode (SHEET mode only) */}
                {product.pricing_mode === 'SHEET' && (
                  <div>
                    <label className="block text-sm font-medium text-stone-600 dark:text-stone-300 mb-1.5">Color</label>
                    <div className="grid grid-cols-2 gap-2">
                      <button
                        type="button"
                        onClick={() => updateForm({ color_mode: 'COLOR' })}
                        className={cn(
                          'rounded-lg border px-3 py-2 text-sm font-medium transition-all flex items-center justify-center gap-1',
                          form.color_mode === 'COLOR'
                            ? 'border-amber-400 bg-amber-50 dark:bg-amber-900/20 text-amber-700 dark:text-amber-300 ring-1 ring-amber-400/50'
                            : 'border-stone-200 dark:border-stone-600 text-stone-600 dark:text-stone-300 hover:border-stone-300'
                        )}
                      >
                        <Palette className="h-4 w-4" />
                        Color
                      </button>
                      <button
                        type="button"
                        onClick={() => updateForm({ color_mode: 'BW' })}
                        className={cn(
                          'rounded-lg border px-3 py-2 text-sm font-medium transition-all',
                          form.color_mode === 'BW'
                            ? 'border-amber-400 bg-amber-50 dark:bg-amber-900/20 text-amber-700 dark:text-amber-300 ring-1 ring-amber-400/50'
                            : 'border-stone-200 dark:border-stone-600 text-stone-600 dark:text-stone-300 hover:border-stone-300'
                        )}
                      >
                        B&W
                      </button>
                    </div>
                  </div>
                )}

                {/* Paper (SHEET mode) */}
                {product.pricing_mode === 'SHEET' && papers.length > 0 && (
                  <div>
                    <label className="block text-sm font-medium text-stone-600 dark:text-stone-300 mb-1.5">Paper type / grammage</label>
                    <div className="space-y-1.5 max-h-36 overflow-y-auto rounded-lg border border-stone-200 dark:border-stone-600 p-2">
                      {papers.map(p => (
                        <label
                          key={p.id}
                          className={cn(
                            'flex items-center gap-3 rounded-lg px-3 py-2 cursor-pointer transition-colors',
                            form.paper === p.id
                              ? 'bg-amber-50 dark:bg-amber-900/20'
                              : 'hover:bg-stone-50 dark:hover:bg-stone-800/50'
                          )}
                        >
                          <input
                            type="radio"
                            name="paper"
                            checked={form.paper === p.id}
                            onChange={() => updateForm({ paper: p.id })}
                            className="accent-amber-500"
                          />
                          <span className="text-sm text-stone-700 dark:text-stone-200">
                            {p.sheet_size} {p.gsm}gsm {p.paper_type}
                          </span>
                          <span className="ml-auto text-xs text-stone-400">KES {p.selling_price}</span>
                        </label>
                      ))}
                    </div>
                  </div>
                )}

                {/* Material (LARGE_FORMAT mode) */}
                {product.pricing_mode === 'LARGE_FORMAT' && materials.length > 0 && (
                  <div>
                    <label className="block text-sm font-medium text-stone-600 dark:text-stone-300 mb-1.5">Material</label>
                    <div className="space-y-1.5 max-h-36 overflow-y-auto rounded-lg border border-stone-200 dark:border-stone-600 p-2">
                      {materials.map(m => (
                        <label
                          key={m.id}
                          className={cn(
                            'flex items-center gap-3 rounded-lg px-3 py-2 cursor-pointer transition-colors',
                            form.material === m.id
                              ? 'bg-amber-50 dark:bg-amber-900/20'
                              : 'hover:bg-stone-50 dark:hover:bg-stone-800/50'
                          )}
                        >
                          <input
                            type="radio"
                            name="material"
                            checked={form.material === m.id}
                            onChange={() => updateForm({ material: m.id })}
                            className="accent-amber-500"
                          />
                          <span className="text-sm text-stone-700 dark:text-stone-200">
                            {m.material_type ?? m.name}
                          </span>
                          <span className="ml-auto text-xs text-stone-400">
                            KES {m.selling_price}/{m.unit}
                          </span>
                        </label>
                      ))}
                    </div>
                  </div>
                )}

                {/* Finishing options */}
                {finishingRates.length > 0 && (
                  <div>
                    <label className="block text-sm font-medium text-stone-600 dark:text-stone-300 mb-1.5">Finishing</label>
                    <div className="space-y-1.5 max-h-40 overflow-y-auto rounded-lg border border-stone-200 dark:border-stone-600 p-2">
                      {finishingRates.map(fr => {
                        const isChecked = form.finishings.some(f => f.finishing_rate === fr.id)
                        return (
                          <label
                            key={fr.id}
                            className="flex items-center gap-3 rounded-lg px-3 py-2 cursor-pointer transition-colors hover:bg-stone-50 dark:hover:bg-stone-800/50"
                          >
                            <input
                              type="checkbox"
                              checked={isChecked}
                              onChange={e => toggleFinishing(fr.id, e.target.checked)}
                              className="accent-amber-500 h-4 w-4 rounded"
                            />
                            <span className="text-sm text-stone-700 dark:text-stone-200 flex-1">{fr.name}</span>
                            <span className="text-xs text-stone-400">KES {fr.price}</span>
                          </label>
                        )
                      })}
                    </div>
                  </div>
                )}

                {/* Hint for complete quote */}
                {needsPaperOrFinishing && (
                  <div className="rounded-lg border border-amber-200 dark:border-amber-800 bg-amber-50/50 dark:bg-amber-900/20 p-3 text-sm text-amber-800 dark:text-amber-200">
                    <p className="font-medium flex items-center gap-2">
                      <Lightbulb className="h-4 w-4 shrink-0" />
                      For a complete quote
                    </p>
                    <ul className="mt-1 ml-6 list-disc space-y-0.5 text-amber-700 dark:text-amber-300">
                      {product.pricing_mode === 'SHEET' && papers.length > 0 && !form.paper && (
                        <li>Select paper for accurate pricing</li>
                      )}
                      {product.pricing_mode === 'LARGE_FORMAT' && materials.length > 0 && !form.material && (
                        <li>Select material for accurate pricing</li>
                      )}
                      {finishingRates.length > 0 && form.finishings.length === 0 && (
                        <li>Consider adding finishing (lamination, binding, etc.)</li>
                      )}
                    </ul>
                  </div>
                )}

                {/* Special instructions */}
                <div>
                  <label className="block text-sm font-medium text-stone-600 dark:text-stone-300 mb-1.5">
                    Special instructions
                  </label>
                  <textarea
                    value={form.special_instructions}
                    onChange={e => updateForm({ special_instructions: e.target.value })}
                    placeholder="Any notes for the shop (optional)"
                    rows={2}
                    className="w-full rounded-lg border border-stone-300 dark:border-stone-600 bg-white dark:bg-stone-800 px-3 py-2 text-sm text-stone-800 dark:text-stone-100 placeholder-stone-400 focus:outline-none focus:ring-2 focus:ring-amber-400 resize-none"
                  />
                </div>

                {/* Price preview section */}
                <div className="rounded-xl border border-amber-200 dark:border-amber-800/50 bg-amber-50/50 dark:bg-amber-900/10 p-4 space-y-2">
                  <p className="text-xs font-semibold uppercase tracking-wider text-amber-600 dark:text-amber-400">
                    Quote Summary
                  </p>
                  <div className="flex justify-between text-sm">
                    <span className="text-stone-500 dark:text-stone-400">Product</span>
                    <span className="font-medium text-stone-800 dark:text-stone-100">{product.name}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-stone-500 dark:text-stone-400">Quantity</span>
                    <span className="font-medium text-stone-800 dark:text-stone-100">{form.quantity} pcs</span>
                  </div>
                  {product.pricing_mode === 'SHEET' && (
                    <div className="flex justify-between text-sm">
                      <span className="text-stone-500 dark:text-stone-400">Sides</span>
                      <span className="font-medium text-stone-800 dark:text-stone-100">
                        {form.sides === 'DUPLEX' ? 'Double-sided' : 'Single-sided'}
                      </span>
                    </div>
                  )}
                  {product.pricing_mode === 'SHEET' && (
                    <div className="flex justify-between text-sm">
                      <span className="text-stone-500 dark:text-stone-400">Color</span>
                      <span className="font-medium text-stone-800 dark:text-stone-100">
                        {form.color_mode === 'COLOR' ? 'Full Color' : 'Black & White'}
                      </span>
                    </div>
                  )}
                  {selectedPaperLabel && (
                    <div className="flex justify-between text-sm">
                      <span className="text-stone-500 dark:text-stone-400">Paper</span>
                      <span className="font-medium text-stone-800 dark:text-stone-100">{selectedPaperLabel}</span>
                    </div>
                  )}
                  {selectedMaterialLabel && (
                    <div className="flex justify-between text-sm">
                      <span className="text-stone-500 dark:text-stone-400">Material</span>
                      <span className="font-medium text-stone-800 dark:text-stone-100">{selectedMaterialLabel}</span>
                    </div>
                  )}
                  {selectedFinishingLabels.length > 0 && (
                    <div className="flex justify-between text-sm">
                      <span className="text-stone-500 dark:text-stone-400">Finishing</span>
                      <span className="font-medium text-stone-800 dark:text-stone-100 text-right max-w-[60%]">
                        {selectedFinishingLabels.join(', ')}
                      </span>
                    </div>
                  )}

                  {estimatedTotal && (
                    <div className="border-t border-amber-200/60 dark:border-amber-800/30 pt-2 space-y-1">
                      <div className="flex justify-between items-baseline">
                        <span className="font-semibold text-stone-800 dark:text-stone-100">Est. total</span>
                        <span className="text-lg font-bold text-amber-600 dark:text-amber-400">
                          KES {estimatedTotal.total.toLocaleString()}
                        </span>
                      </div>
                      <div className="flex justify-between text-sm text-stone-400">
                        <span>Per item</span>
                        <span>KES {estimatedTotal.perUnit.toFixed(2)}</span>
                      </div>
                    </div>
                  )}
                  <p className="text-xs text-stone-400 pt-1">
                    Final price computed by the shop after submission.
                  </p>
                </div>

                {/* Actions */}
                <div className="flex gap-3 pt-2">
                  <button
                    type="button"
                    onClick={onClose}
                    className="flex-1 px-4 py-2.5 rounded-xl border border-stone-200 dark:border-stone-600 text-stone-600 dark:text-stone-300 text-sm font-medium hover:bg-stone-50 dark:hover:bg-stone-800 transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={submitting}
                    className="flex-1 px-4 py-2.5 rounded-xl bg-amber-500 hover:bg-amber-600 text-white text-sm font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                  >
                    {submitting ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <Plus className="h-4 w-4" />
                    )}
                    {submitting ? 'Adding…' : 'Add to Quote'}
                  </button>
                </div>
              </form>
            </>
          )}
        </div>
      </div>
    </div>
  )
}
